const numoniLogoLight = '/assets/icons/numoni-logo-light.svg';
const numoniLogoDark = '/assets/icons/numoni-logo-dark.svg';
const crownIcon = '/assets/icons/crown.svg';
const notificationIcon = '/assets/icons/notification-01.svg';
const messageIcon = '/assets/icons/message-icon.svg';
const profileIcon = '/assets/icons/profile-icon.svg';
const blueVerifiedIcon = '/assets/icons/blue-verified-icon.svg';
const rightArrowIcon = '/assets/icons/arrow-right.svg';
const rightArrowWhiteIcon = '/assets/icons/arrow-right-white.svg';
const branchIcon = '/assets/icons/branch-icon.svg';
const rewardIcon = '/assets/icons/reward-icon.svg';
const peopleIcon = '/assets/icons/people.svg';
const emptyBranchIcon = '/assets/icons/empty-icon.svg';
const dealIcon = '/assets/icons/deal.svg';
const graphDirectionIcon = '/assets/icons/graph-direction-icon.svg';
const phoneNotificationIcon = '/assets/icons/phone-notification-icon.svg';
const musicPauseIcon = '/assets/icons/music-pause-icon.svg';
const cashBackIcon = '/assets/icons/cash-back-icon.svg';
const storeIcon = '/assets/icons/store-icon.svg';
const NigeriaIcon = '/assets/icons/nigeria-icon.svg';
const pointIcon = '/assets/icons/points.svg';
const peopleGrayIcon = '/assets/icons/people-gray.svg';
const successIconCheck = '/assets/icons/success-check-icon.svg';
const verifyIcon = '/assets/icons/verify.svg';
const star = '/assets/icons/star.svg';
const branchCloseIcon = '/assets/icons/branch-close-icon.svg';
const editIcon = '/assets/icons/edit-icon.svg';

export { blueVerifiedIcon, branchCloseIcon, branchIcon, cashBackIcon, crownIcon, dealIcon, editIcon, emptyBranchIcon, graphDirectionIcon, messageIcon, musicPauseIcon, NigeriaIcon, notificationIcon, numoniLogoDark, numoniLogoLight, peopleGrayIcon, peopleIcon, phoneNotificationIcon, pointIcon, profileIcon, rewardIcon, rightArrowIcon, rightArrowWhiteIcon, star, storeIcon, successIconCheck, verifyIcon };

