
//auth
const SIGN_IN_URL: string = '/auth/sign-in';



const DASHBOARD_URL: string = '/dashboard';
const BRANCH_LEVEL_URL: string = `${DASHBOARD_URL}/branch-level`;
const REWARD_TABLE_URL: string = `${DASHBOARD_URL}/reward-table`;
const DEALS_AND_PROMOS_URL: string = `${DASHBOARD_URL}/deals-and-promos`;
const CHARITY_ORGS_URL: string = `${DASHBOARD_URL}/charity-orgs`;


//admin
const ADMIN_URL: string = '/admin';
const ADMIN_MERCHANTS_URL: string = `${ADMIN_URL}/merchants`;
const ADMIN_MERCHANTS_ADD_URL: string = `${ADMIN_MERCHANTS_URL}/add-merchant`;
const ADMIN_MERCHANTS_ANALYTICS_URL: string = `${ADMIN_MERCHANTS_URL}/analytics`;
const ADMIN_MERCHANTS_TRANSACTIONS_URL: string = `${ADMIN_MERCHANTS_URL}/transactions`;
const ADMIN_MERCHANTS_REPORTS_URL: string = `${ADMIN_MERCHANTS_URL}/reports`;
const ADMIN_MERCHANTS_LOGS_URL: string = `${ADMIN_MERCHANTS_URL}/logs`;
const ADMIN_MERCHANTS_ROLES_URL: string = `${ADMIN_MERCHANTS_URL}/roles`;

export { ADMIN_MERCHANTS_ADD_URL, ADMIN_MERCHANTS_ANALYTICS_URL, ADMIN_MERCHANTS_LOGS_URL, ADMIN_MERCHANTS_REPORTS_URL, ADMIN_MERCHANTS_ROLES_URL, ADMIN_MERCHANTS_TRANSACTIONS_URL, ADMIN_MERCHANTS_URL, ADMIN_URL, BRANCH_LEVEL_URL, CHARITY_ORGS_URL, DASHBOARD_URL, DEALS_AND_PROMOS_URL, REWARD_TABLE_URL, SIGN_IN_URL };

